;; -*- coding: utf-8 -*-

(require 'anything)
(require 'minor-mode-hack)
(require 'recentf-ext)
(require 'redo+)
(require 'bm)
(require 'css-mode)
(require 'ert)
(require 'js2-mode)
(require 'marmalade)
(require 'slime)
(require 'yasnippet)
(require 'undo-tree)
(require 'c-eldoc)
(require 'bookmark+)
(require 'wgrep)
(require 'smartrep)
(require 'ac-slime)
(require 'slime-fuzzy)
(require 'org)
(require 'highlight-symbol)
(require 'scheme-complete)
(require 'tabbar)
(require 'gist)
;;
(require 'quack)
(require 'geiser)
(require 'auto-complete)
(require 'sdic)